name: wcy
version: '1.0.0'
profile: wcy

require-dbt-version: ">=1.8.0,<2.0.0"

model-paths: ['models']
seed-paths: ['seeds']
test-paths: ['tests']
macro-paths: ['macros']

target-path: 'target'
clean-targets: ['target', 'dbt_packages']

vars:
  raw_dataset: "{{ env_var('DBT_RAW_DATASET', 'raw') }}"
  growing_season_start: '04-01'
  growing_season_end: '10-31'

seeds:
  wcy:
    +schema: staging

models:
  wcy:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
